[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
    { id = "RUSTSEC-2024-0370", reason = "`proc-macro-error` is unmaintained, but foundry relies on it" },
    { id = "RUSTSEC-2024-0388", reason = '`derivative` is unmaintained, crypto dependenicies (boojum, circuit_encodings and others) rely on it' },
    { id = "RUSTSEC-2024-0436", reason = "`paste` is unmaintained, but is still widely used" },
    { id = "RUSTSEC-2024-0437", reason = '`protobuf` needs to be updated to >=3.7.0, but is locked to 3.3.0 by foundry; will be resolved once we get rid of dependency on foundry-anvil' },
    { id = "RUSTSEC-2024-0384", reason = "`instant` is used transitively and we do not rely on problematic behavior" },
    { id = "RUSTSEC-2025-0009", reason = "`ring` is used in test or non-QUIC contexts; we do not encrypt >64GB chunks" },
    { id = "RUSTSEC-2025-0010", reason = "`ring` <0.17 is used by transitive deps; upgrading is not currently possible" },
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "Unlicense",
    "MPL-2.0",
    "CC0-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Zlib",
    "OpenSSL",
    "Apache-2.0 WITH LLVM-exception",
    "0BSD",
    "BSL-1.0",
    "Unicode-3.0",
    "CDDL-1.0",
    "CDLA-Permissive-2.0",
]
exceptions = [
    # exceptions are in place due to https://github.com/matter-labs/zksync-os
    # CC0 is a bit unclear about source code: https://tldrlegal.com/license/creative-commons-cc0-1.0-universal
    { allow = ["CC0-1.0"], name = "tiny-keccak" },
    { allow = ["OpenSSL"], crate = "ring" },
]
confidence-threshold = 0.8

[[licenses.clarify]]
crate = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "allow"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
