//
// AUTOGENERATED BASED ON A SET OF JSON FILES, DO NOT EDIT MANUALLY
//
use crate::identifier::Identifier;
#[derive(Debug, Clone, PartialEq, Eq, serde :: Serialize, serde :: Deserialize)]
pub struct UntypedErrorObject {
    pub identifier: Identifier,
    pub name: String,
    pub fields: serde_json::Map<String, serde_json::Value>,
    pub raw: serde_json::Value,
}
