name: run

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: unit-tests
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-24.04-github-hosted-16core]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install cargo-nextest
      run: cargo install cargo-nextest

    - name: Run tests
      run: cargo nextest run
